import type { Metadata } from "next";
import { AppHeader } from "~/components/app-header/app-header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col gap-4 ">
      <AppHeader />
      <main className="container mx-auto px-4">
        {children}
      </main>
    </div>
  );
}
